### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by nhocki** [febuiles/s3share#5]
No es mucho pedir???????? ;-) Algo más verbose que uno sepa que está haciendo algo!

**Comment by febuiles** [comment]
https://github.com/bitboxer/simple_progressbar/blob/master/lib/simple_progressbar.rb probablemente lo haga, esta noche le trabajo un rato.

**Comment by febuiles** [comment]
Fixed. No pude usar ProgressBar por la forma en la que hace el upload aws-s3 pero ya al menos hay un indicador que te dice cuando está subiendo.
